import { useState, createContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import KeySelect from "../components/KeySelect";
import ScaleSelect from "../components/ScaleSelect";
import Scale from "../components/Scale";
import Script from "next/script";

const ScaleContext = createContext({});

const Home: NextPage = () => {
  const [scaleType, setScaleType] = useState("major");
  const [key, setKey] = useState("F");
  return (
    <div>
      <Script src="https://unpkg.com/vextab@3.0.6/releases/main.dev.js"></Script>
      <Head>
        <title>Guitar Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ScaleContext.Provider value={{scaleType, key}}>
          <ScaleSelect setScaleType={setScaleType} />
          <KeySelect setKey={setKey} scaleType={scaleType} />
          <Scale scaleKey={key} scaleType={scaleType} />
        </ScaleContext.Provider>
      </main>

      <footer>
        <a
          href="https://github.com/Digald"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Mark Alaniz
        </a>
      </footer>
    </div>
  );
};

export default Home;
