import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Scale from "../components/Scale";
import Script from "next/script";
import NavBar from "../components/NavBar";
import { ButtonListItem, SetExerciseList } from "../components/utils/types";

const Home: NextPage = () => {
  const [scaleType, setScaleType] = useState("major");
  const [key, setKey] = useState("F");
  const [exerciseList, setExerciseList] = useState<ButtonListItem[]>([]);

  return (
    <div>
      <Script src="https://unpkg.com/vextab@3.0.6/releases/main.dev.js"></Script>
      <Head>
        <title>Guitar Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar
          setScaleType={setScaleType}
          scaleType={scaleType}
          setKey={setKey}
          // @ts-ignore
          setExerciseList={setExerciseList}
          exerciseList={exerciseList}
        />
        {Array.isArray(exerciseList) &&
          exerciseList?.map((exercise: ButtonListItem, index: number) => (
            <Scale
              key={exercise.name}
              scaleKey={key}
              scaleType={scaleType}
              id={`i-${index}`}
              scaleName={exercise.name}
              parseScale={exercise.function}
              options={exercise.options || {}}
            />
          ))}
      </main>

      <footer>
        <a
          href="https://github.com/Digald"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Mark Alaniz
        </a>
      </footer>
    </div>
  );
};

export default Home;
